# Generated by Django 3.1.2 on 2020-10-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201026_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlstate',
            name='token',
            field=models.CharField(default='336f728dd5d6403526e398a7fac9107540c32ae40fa157dd581fa99553f04436', max_length=255),
        ),
    ]
