# Generated by Django 3.1.2 on 2020-10-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20201026_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlstate',
            name='token',
            field=models.CharField(default='579f93cae548260f0f419ca33f34af77ad0ea76afe914b4a9607230080e8578e', max_length=255),
        ),
    ]
