# Generated by Django 3.1.2 on 2020-10-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20201027_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlstate',
            name='token',
            field=models.CharField(default='58b36f358d06218d7456ed2e4e33ad0fe1e9b16ef6bc642406fe492dc01af31e', max_length=255),
        ),
    ]
