# Generated by Django 3.1.2 on 2020-10-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20201028_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlstate',
            name='token',
            field=models.CharField(default='169175ccefbbef54c8bd5fed7eae475651357b1a2293c280d0541aac9fe2d61d', max_length=255),
        ),
    ]
