# Generated by Django 3.1.2 on 2020-10-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20201028_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlstate',
            name='token',
            field=models.CharField(default='a4b8e9823138535c2fb83ae3bae88cb2b018ca1bfbb66c0f17a365eaae84157e', max_length=255),
        ),
    ]
