# Generated by Django 3.1.2 on 2020-10-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20201028_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlstate',
            name='token',
            field=models.CharField(default='e8cbd621f47189eb6623297f35eb116a252a57b888bd9fd91bc8c421cce4c5c3', max_length=255),
        ),
    ]
