# Generated by Django 3.1.2 on 2020-10-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20201028_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlstate',
            name='token',
            field=models.CharField(default='f8b696c95d27e25df57ed1f42a7397977d6d0201f4a2c3c14d3a9179b52c3201', max_length=255),
        ),
    ]
