# Generated by Django 3.1.2 on 2020-10-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20201028_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlstate',
            name='token',
            field=models.CharField(default='4043460917c97d30a4faa147028aa0bc81ac1340323d519736179947d6804718', max_length=255),
        ),
    ]
