# Generated by Django 3.1.2 on 2020-10-10 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_id', models.IntegerField(default=0)),
                ('first_name', models.CharField(default='-', max_length=255)),
                ('last_name', models.CharField(default='-', max_length=255)),
                ('nickname', models.CharField(default='-', max_length=255)),
                ('email', models.EmailField(default='-', max_length=255)),
                ('phone', models.CharField(default='-', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_id', models.IntegerField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('status', models.CharField(default='-', max_length=20)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sales.buyer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('full_unit_price', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sales.sale')),
            ],
        ),
    ]
