# Generated by Django 3.1.2 on 2020-10-25 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 25, 0, 5, 34, 403850)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 25, 0, 5, 58, 753816)),
            preserve_default=False,
        ),
    ]
