# Generated by Django 3.1.2 on 2020-10-28 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20201027_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_id', models.CharField(max_length=20)),
                ('mode', models.CharField(default='', max_length=20)),
                ('status', models.CharField(default='-', max_length=100)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('logistic', models.CharField(default='No especificado', max_length=50)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.sale')),
            ],
        ),
    ]
