# Generated by Django 3.1.2 on 2020-10-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='ml_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='ml_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
