# Generated by Django 3.1.2 on 2020-10-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ml_id',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
