# Generated by Django 3.1.2 on 2020-10-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201026_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ml_id',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
