# Generated by Django 3.1.2 on 2020-10-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variation_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
