# Generated by Django 3.1.2 on 2020-10-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201028_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
